"use client";

import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type UiLanguage = "en" | "sr-Latn";

type UiStrings = Record<string, string>;

const STORAGE_KEY = "shadowbroker-ui-language";

const STRINGS: Record<UiLanguage, UiStrings> = {
    en: {
        "app.title": "SHADOWBROKER",
        "app.subtitle": "GLOBAL THREAT INTERCEPT",
        "ui.coordinates": "COORDINATES",
        "ui.location": "LOCATION",
        "ui.style": "STYLE",
        "ui.restore": "RESTORE UI",
        "ui.findPlaceholder": "Find aircraft or vessel...",
        "ui.results": "RESULTS",
        "ui.clickToLocate": "CLICK TO LOCATE",
        "ui.noMatches": "NO MATCHING ASSETS",
        "ui.displayConfig": "DISPLAY CONFIG",
        "ui.bloom": "BLOOM",
        "ui.sharpen": "SHARPEN",
        "ui.hud": "HUD",
        "ui.layout": "LAYOUT",
        "ui.tactical": "Tactical",
        "ui.clearUi": "CLEAR UI (TACTICAL MODE)",
        "ui.settings": "SYSTEM CONFIG",
        "ui.settingsSubtitle": "API KEY REGISTRY",
        "ui.settingsInfo": "API keys are stored locally in the backend .env file. Keys marked with the key icon are required for full functionality. Public APIs need no key.",
        "ui.language": "LANGUAGE",
        "ui.languageEnglish": "English",
        "ui.languageSerbian": "Serbian Latin",
        "ui.key": "KEY",
        "ui.registeredApis": "REGISTERED APIs",
        "ui.keysConfigured": "KEYS CONFIGURED",
        "ui.service": "service",
        "ui.services": "services",
        "ui.keySet": "KEY SET",
        "ui.public": "PUBLIC",
        "ui.enterKey": "Enter API key...",
        "ui.save": "SAVE",
        "ui.hideKey": "Hide key",
        "ui.revealKey": "Reveal key",
        "ui.copyKey": "Copy to clipboard",
        "ui.mapLegend": "MAP LEGEND",
        "ui.legendSubtitle": "ICON REFERENCE KEY",
        "ui.legendFooter": "ICON DEFINITIONS ACROSS",
        "ui.legendCategories": "CATEGORIES",
        "ui.systemSettings": "System Settings",
        "ui.mapLegendKey": "Map Legend / Icon Key",
        "ui.dataLayers": "DATA LAYERS",
        "ui.live": "LIVE",
        "ui.off": "OFF",
        "ui.on": "ON",
        "layer.commercialFlights": "Commercial Flights",
        "layer.privateFlights": "Private Flights",
        "layer.privateJets": "Private Jets",
        "layer.militaryFlights": "Military Flights",
        "layer.trackedAircraft": "Tracked Aircraft",
        "layer.earthquakes": "Earthquakes (24h)",
        "layer.satellites": "Satellites",
        "layer.shipsImportant": "Carriers / Mil / Cargo",
        "layer.shipsCivilian": "Civilian Vessels",
        "layer.shipsPassenger": "Cruise / Passenger",
        "layer.ukraineFrontline": "Ukraine Frontline",
        "layer.globalIncidents": "Global Incidents",
        "layer.cctv": "CCTV Mesh",
        "layer.gpsJamming": "GPS Jamming",
        "layer.dayNight": "Day / Night Cycle",
        "legend.commercialAviation": "COMMERCIAL AVIATION",
        "legend.privateAviation": "PRIVATE AVIATION",
        "legend.privateJets": "PRIVATE JETS",
        "legend.militaryGov": "MILITARY / GOVERNMENT",
        "legend.militaryAviation": "MILITARY AVIATION",
        "legend.trackedAircraft": "TRACKED AIRCRAFT (ALERT)",
        "legend.maritime": "MARITIME",
        "legend.geophysical": "GEOPHYSICAL",
        "legend.satellites": "SATELLITES",
        "legend.incidentsIntelligence": "INCIDENTS & INTELLIGENCE",
        "legend.newsOsint": "NEWS & OSINT",
        "legend.gpsJamming": "GPS JAMMING / INTERFERENCE",
        "legend.surveillanceCctv": "SURVEILLANCE / CCTV",
        "legend.overlays": "OVERLAYS",
        "legend.intelligence": "INTELLIGENCE / SIGINT",
        "legend.surveillance": "SURVEILLANCE",
        "legend.geospatial": "GEOSPATIAL",
        "search.commercial": "COMMERCIAL",
        "search.private": "PRIVATE",
        "search.military": "MILITARY",
        "search.tracked": "TRACKED",
        "search.maritime": "MARITIME",
        "search.database": "DATABASE",
        "ui.globalMarkets": "GLOBAL MARKETS",
        "ui.defenseSecTickers": "DEFENSE SEC TICKERS",
        "ui.commodityIndex": "COMMODITY INDEX",
        "ui.dataFilters": "DATA FILTERS",
        "ui.active": "ACTIVE",
        "ui.clearAllFilters": "CLEAR ALL FILTERS",
        "ui.commercialFlights": "COMMERCIAL FLIGHTS",
        "ui.privateFlights": "PRIVATE / JETS",
        "ui.militaryFlights": "MILITARY",
        "ui.trackedAircraft": "TRACKED AIRCRAFT",
        "ui.maritimeVessels": "MARITIME VESSELS",
        "ui.departure": "DEPARTURE",
        "ui.arrival": "ARRIVAL",
        "ui.airline": "AIRLINE",
        "ui.callsignReg": "CALLSIGN / REG",
        "ui.aircraftType": "AIRCRAFT TYPE",
        "ui.countryReg": "COUNTRY / REG",
        "ui.category": "CATEGORY",
        "ui.operatorEntity": "OPERATOR / ENTITY",
        "ui.vesselName": "VESSEL NAME",
        "ui.vesselType": "VESSEL TYPE",
        "ui.search": "Search",
        "ui.available": "AVAILABLE",
        "ui.selected": "SELECTED",
        "ui.noMatchingResults": "NO MATCHING RESULTS",
        "ui.clear": "CLEAR",
        "ui.cancel": "CANCEL",
        "ui.apply": "APPLY",
        "ui.systemError": "SYSTEM ERROR",
        "ui.componentFailedToRender": "failed to render",
        "ui.retry": "RETRY",
        "ui.sigintIntercept": "SIGINT INTERCEPT",
        "ui.noSignal": "NO SIGNAL",
        "ui.awaitingTuning": "AWAITING TUNING...",
        "ui.scanning": "SCANNING...",
        "ui.autoScan": "AUTO SCAN",
        "ui.eavesdrop": "EAVESDROP",
        "ui.clickGlobeIntercept": "Click on the globe to intercept local signals",
        "ui.volume": "Volume",
        "ui.searchingFrequencies": "SEARCHING FREQUENCIES...",
        "ui.triangulatingSignal": "TRIANGULATING SIGNAL...",
        "ui.noRecentComms": "NO RECENT COMMS",
        "ui.noLocalRepeatersFound": "NO LOCAL REPEATERS FOUND",
        "ui.regionDossier": "REGION DOSSIER",
        "ui.compilingIntelligence": "COMPILING INTELLIGENCE...",
        "ui.countryLevel": "COUNTRY LEVEL",
        "ui.official": "OFFICIAL",
        "ui.country": "COUNTRY",
        "ui.leader": "LEADER",
        "ui.government": "GOVERNMENT",
        "ui.population": "POPULATION",
        "ui.capital": "CAPITAL",
        "ui.languages": "LANGUAGES",
        "ui.currency": "CURRENCY",
        "ui.region": "REGION",
        "ui.area": "AREA",
        "ui.localLevel": "LOCAL LEVEL",
        "ui.locality": "LOCALITY",
        "ui.stateProvince": "STATE/PROVINCE",
        "ui.type": "TYPE",
        "ui.intelUnavailable": "INTEL UNAVAILABLE",
        "ui.unknown": "UNKNOWN",
        "ui.unknownRegion": "UNKNOWN REGION",
        "ui.unknownMount": "UNKNOWN MOUNT",
        "ui.alert": "ALERT",
        "ui.militaryAsset": "MILITARY ASSET",
        "ui.privateJet": "PRIVATE JET",
        "ui.privateGa": "PRIVATE / GA",
        "ui.commercialFlight": "COMMERCIAL FLIGHT",
        "ui.operator": "OPERATOR",
        "ui.registration": "REGISTRATION",
        "ui.aircraft": "AIRCRAFT",
        "ui.intelTag": "INTEL TAG",
        "ui.secondary": "SECONDARY",
        "ui.detail": "DETAIL",
        "ui.altitude": "ALTITUDE",
        "ui.groundSpeed": "GROUND SPEED",
        "ui.heading": "HEADING",
        "ui.squawk": "SQUAWK",
        "ui.flightRecord": "FLIGHT RECORD",
        "ui.route": "ROUTE",
        "ui.vesselRecord": "VESSEL RECORD",
        "ui.destination": "DESTINATION",
        "ui.callsign": "CALLSIGN",
        "ui.imoNumber": "IMO NUMBER",
        "ui.flagState": "FLAG STATE",
        "ui.speedSog": "SPEED (SOG)",
        "ui.courseCog": "COURSE (COG)",
        "ui.description": "DESCRIPTION",
        "ui.reportedTime": "REPORTED TIME",
        "ui.viewLiveuamapReport": "View Liveuamap Report",
        "ui.globalThreatIntercept": "GLOBAL THREAT INTERCEPT",
        "ui.viewOnMarineTraffic": "View on MarineTraffic",
        "ui.collapse": "[- COLLAPSE]",
        "ui.sources": "SOURCES",
        "ui.militaryBogeyIntercept": "MILITARY BOGEY INTERCEPT",
        "ui.privateTransponder": "PRIVATE TRANSPONDER",
        "ui.privateJetTransponder": "PRIVATE JET TRANSPONDER",
        "ui.commercialTransponder": "COMMERCIAL TRANSPONDER",
        "ui.aisTankerIntercept": "AIS TANKER INTERCEPT",
        "ui.aisCargoIntercept": "AIS CARGO INTERCEPT",
        "ui.aisPassengerVessel": "AIS PASSENGER VESSEL",
        "ui.aisYachtSignal": "AIS YACHT SIGNAL",
        "ui.aisMilitaryVessel": "AIS MILITARY VESSEL",
        "ui.carrierStrikeGroup": "CARRIER STRIKE GROUP",
        "ui.aisVesselSignal": "AIS VESSEL SIGNAL",
        "ui.militaryIncidentCluster": "MILITARY INCIDENT CLUSTER",
        "ui.vessel": "VESSEL",
        "ui.aircraftCarrier": "AIRCRAFT CARRIER",
        "ui.tanker": "TANKER",
        "ui.cargoVessel": "CARGO VESSEL",
        "ui.passengerCruise": "PASSENGER / CRUISE",
        "ui.privateYacht": "PRIVATE YACHT",
        "ui.militaryVessel": "MILITARY VESSEL",
        "ui.latestReports": "LATEST REPORTS:",
        "ui.viewSourceReport": "View Source Report",
        "ui.regionalTacticalEvent": "REGIONAL TACTICAL EVENT",
        "ui.viewDetails": "View Details",
        "ui.newsOnTheGround": "NEWS ON THE GROUND",
        "ui.noArticlesAvailable": "No articles available.",
        "ui.viewSourceArticle": "View Source Article",
        "ui.threatIntercept": "THREAT INTERCEPT",
        "ui.viewIntelSource": "View Intel Source",
        "ui.viewHistoryLog": "View History Log",
        "ui.aeronauticalHub": "AERONAUTICAL HUB",
        "ui.facilityName": "FACILITY NAME",
        "ui.status": "STATUS",
        "ui.operational": "OPERATIONAL",
        "ui.locationPrefix": "LOCATION:",
        "ui.articleCount": "ARTICLE COUNT",
        "ui.headline": "HEADLINE",
        "ui.reference": "REFERENCE",
        "ui.time": "TIME",
        "ui.source": "SOURCE",
    },
    "sr-Latn": {
        "app.title": "SENKA",
        "app.subtitle": "GLOBALNO PRESRETANJE PRETNJI",
        "ui.coordinates": "KOORDINATE",
        "ui.location": "LOKACIJA",
        "ui.style": "STIL",
        "ui.restore": "VRATI UI",
        "ui.findPlaceholder": "Pronađi letelicu ili plovilo...",
        "ui.results": "REZULTATI",
        "ui.clickToLocate": "KLIKNI ZA LOKACIJU",
        "ui.noMatches": "NEMA PODUDARNIH SADRŽAJA",
        "ui.displayConfig": "PRIKAZ KONFIG",
        "ui.bloom": "BLOOM",
        "ui.sharpen": "OŠTRINA",
        "ui.hud": "HUD",
        "ui.layout": "RASPORED",
        "ui.tactical": "Taktički",
        "ui.clearUi": "OBRIŠI UI (TAKTIČKI REŽIM)",
        "ui.settings": "SISTEMSKA PODEŠAVANJA",
        "ui.settingsSubtitle": "REGISTAR API KLJUČEVA",
        "ui.settingsInfo": "API ključevi se čuvaju lokalno u backend .env datoteci. Ključevi označeni ikonicom ključa potrebni su za punu funkcionalnost. Javnim API-jima ne treba ključ.",
        "ui.language": "JEZIK",
        "ui.languageEnglish": "Engleski",
        "ui.languageSerbian": "Srpski latinica",
        "ui.key": "KLJUČ",
        "ui.registeredApis": "REGISTROVANI API-JI",
        "ui.keysConfigured": "PODEŠENI KLJUČEVI",
        "ui.service": "servis",
        "ui.services": "servisa",
        "ui.keySet": "KLJUČ POSTAVLJEN",
        "ui.public": "JAVNI",
        "ui.enterKey": "Unesi API ključ...",
        "ui.save": "SAČUVAJ",
        "ui.hideKey": "Sakrij ključ",
        "ui.revealKey": "Prikaži ključ",
        "ui.copyKey": "Kopiraj u međuspremnik",
        "ui.mapLegend": "LEGENDA MAPE",
        "ui.legendSubtitle": "REFERENTNI KLJUČ IKONA",
        "ui.legendFooter": "DEFINICIJE IKONA U OKVIRU",
        "ui.legendCategories": "KATEGORIJA",
        "ui.systemSettings": "Sistemska podešavanja",
        "ui.mapLegendKey": "Legenda mape / ključ ikona",
        "ui.dataLayers": "SLOJEVI PODATAKA",
        "ui.live": "UŽIVO",
        "ui.off": "ISKLJ",
        "ui.on": "UKLJ",
        "layer.commercialFlights": "Komercijalni letovi",
        "layer.privateFlights": "Privatni letovi",
        "layer.privateJets": "Privatni džetovi",
        "layer.militaryFlights": "Vojni letovi",
        "layer.trackedAircraft": "Praćene letelice",
        "layer.earthquakes": "Zemljotresi (24h)",
        "layer.satellites": "Sateliti",
        "layer.shipsImportant": "Nosaci / vojne / teretne",
        "layer.shipsCivilian": "Civilna plovila",
        "layer.shipsPassenger": "Kruzeri / putnički",
        "layer.ukraineFrontline": "Ukrajinska linija fronta",
        "layer.globalIncidents": "Globalni incidenti",
        "layer.cctv": "CCTV mreža",
        "layer.gpsJamming": "GPS ometanje",
        "layer.dayNight": "Dan / noć ciklus",
        "legend.commercialAviation": "KOMERCIJALNO VAZDUHOPLOVSTVO",
        "legend.privateAviation": "PRIVATNO VAZDUHOPLOVSTVO",
        "legend.privateJets": "PRIVATNI DŽETOVI",
        "legend.militaryGov": "VOJNO / DRŽAVNO",
        "legend.militaryAviation": "VOJNO VAZDUHOPLOVSTVO",
        "legend.trackedAircraft": "PRAĆENE LETELICE (ALARM)",
        "legend.maritime": "POMORSTVO",
        "legend.geophysical": "GEOFIZIČKI PODACI",
        "legend.satellites": "SATELITI",
        "legend.incidentsIntelligence": "INCIDENTI I OBAVEŠTAJNI PODACI",
        "legend.newsOsint": "VESTI I OSINT",
        "legend.gpsJamming": "GPS OMETANJE / INTERFERENCIJA",
        "legend.surveillanceCctv": "NADZOR / CCTV",
        "legend.overlays": "PREKLAPI",
        "legend.intelligence": "OBAVEŠTAJNI / SIGINT",
        "legend.surveillance": "NADZOR",
        "legend.geospatial": "GEOPROSTORNO",
        "search.commercial": "KOMERCIJALNO",
        "search.private": "PRIVATNO",
        "search.military": "VOJNO",
        "search.tracked": "PRAĆENO",
        "search.maritime": "POMORSKO",
        "search.database": "BAZA PODATAKA",
        "ui.globalMarkets": "GLOBALNA TRŽIŠTA",
        "ui.defenseSecTickers": "ODBRAMBENI SEC TIKERI",
        "ui.commodityIndex": "INDIKS ROBE",
        "ui.dataFilters": "FILTERI PODATAKA",
        "ui.active": "AKTIVNO",
        "ui.clearAllFilters": "OBRIŠI SVE FILTERE",
        "ui.commercialFlights": "KOMERCIJALNI LETOVI",
        "ui.privateFlights": "PRIVATNI / DŽETOVI",
        "ui.militaryFlights": "VOJNI LETOVI",
        "ui.trackedAircraft": "PRAĆENE LETELICE",
        "ui.maritimeVessels": "POMORSKA PLOVILA",
        "ui.departure": "POLAZAK",
        "ui.arrival": "DOLAZAK",
        "ui.airline": "AVIOKOMPANIJA",
        "ui.callsignReg": "POZIVNI ZNAK / REGISTRACIJA",
        "ui.aircraftType": "TIP LETELICE",
        "ui.countryReg": "DRŽAVA / REGISTRACIJA",
        "ui.category": "KATEGORIJA",
        "ui.operatorEntity": "OPERATER / ENTITET",
        "ui.vesselName": "NAZIV PLOVILA",
        "ui.vesselType": "TIP PLOVILA",
        "ui.search": "Pretraži",
        "ui.available": "DOSTUPNO",
        "ui.selected": "ODABRANO",
        "ui.noMatchingResults": "NEMA PODUDARNIH REZULTATA",
        "ui.clear": "OBRIŠI",
        "ui.cancel": "OTKAŽI",
        "ui.apply": "PRIMENI",
        "ui.systemError": "SISTEMSKA GREŠKA",
        "ui.componentFailedToRender": "nije uspelo da se prikaže",
        "ui.retry": "POKUSAJ PONOVO",
        "ui.sigintIntercept": "SIGINT PRESRETANJE",
        "ui.noSignal": "NEMA SIGNALA",
        "ui.awaitingTuning": "NA ČEKANJU...",
        "ui.scanning": "SKENIRANJE...",
        "ui.autoScan": "AUTOMATSKO SKENIRANJE",
        "ui.eavesdrop": "PRESRETNI",
        "ui.clickGlobeIntercept": "Klikni na globus za presretanje lokalnih signala",
        "ui.volume": "Glasnoća",
        "ui.searchingFrequencies": "TRAŽENJE FREKVENCIJA...",
        "ui.triangulatingSignal": "TRIJANGULACIJA SIGNALA...",
        "ui.noRecentComms": "NEMA NEDAVNIH KOMUNIKACIJA",
        "ui.noLocalRepeatersFound": "NISU PRONAĐENI LOKALNI REPEATERI",
        "ui.regionDossier": "REGIONALNI DOSJE",
        "ui.compilingIntelligence": "OBRADA OBAVEŠTAJNIH PODATAKA...",
        "ui.countryLevel": "NIVO DRŽAVE",
        "ui.official": "SLUŽBENO",
        "ui.country": "DRŽAVA",
        "ui.leader": "LIDER",
        "ui.government": "VLADA",
        "ui.population": "STANOVNIŠTVO",
        "ui.capital": "GLAVNI GRAD",
        "ui.languages": "JEZICI",
        "ui.currency": "VALUTA",
        "ui.region": "REGIJA",
        "ui.area": "POVRŠINA",
        "ui.localLevel": "LOKALNI NIVO",
        "ui.locality": "LOKALITET",
        "ui.stateProvince": "DRŽAVA/POKRAJINA",
        "ui.type": "TIP",
        "ui.intelUnavailable": "OBAVEŠTAJNI PODACI NEDOSTUPNI",
        "ui.unknown": "NEPOZNATO",
        "ui.unknownRegion": "NEPOZNATA REGIJA",
        "ui.unknownMount": "NEPOZNAT UREĐAJ",
        "ui.alert": "ALARM",
        "ui.militaryAsset": "VOJNI SISTEM",
        "ui.privateJet": "PRIVATNI DŽET",
        "ui.privateGa": "PRIVATNI / GA",
        "ui.commercialFlight": "KOMERCIJALNI LET",
        "ui.operator": "OPERATER",
        "ui.registration": "REGISTRACIJA",
        "ui.aircraft": "LETELICA",
        "ui.intelTag": "OBAVEŠTAJNA OZNAKA",
        "ui.secondary": "DRUGO",
        "ui.detail": "DETALJ",
        "ui.altitude": "VISINA",
        "ui.groundSpeed": "BRZINA PO ZEMLJI",
        "ui.heading": "SMER",
        "ui.squawk": "SQUAWK",
        "ui.flightRecord": "ZAPIS LETA",
        "ui.route": "RUTA",
        "ui.vesselRecord": "ZAPIS PLOVILA",
        "ui.destination": "ODREDIŠTE",
        "ui.callsign": "POZIVNI ZNAK",
        "ui.imoNumber": "IMO BROJ",
        "ui.flagState": "ZASTAVA DRŽAVE",
        "ui.speedSog": "BRZINA (SOG)",
        "ui.courseCog": "KURS (COG)",
        "ui.description": "OPIS",
        "ui.reportedTime": "PRIJAVLJENO VREME",
        "ui.viewLiveuamapReport": "Prikaži Liveuamap izveštaj",
        "ui.globalThreatIntercept": "GLOBALNO PRESRETANJE PRETNJE",
        "ui.viewOnMarineTraffic": "Prikaži na MarineTraffic",
        "ui.collapse": "[- SKLONI]",
        "ui.sources": "IZVORI",
        "ui.militaryBogeyIntercept": "VOJNI BOGEY PRESRETANJE",
        "ui.privateTransponder": "PRIVATNI TRANSPONDER",
        "ui.privateJetTransponder": "TRANSPONDER PRIVATNOG DŽETA",
        "ui.commercialTransponder": "KOMERCIJALNI TRANSPONDER",
        "ui.aisTankerIntercept": "AIS PRESRETANJE TANKERA",
        "ui.aisCargoIntercept": "AIS PRESRETANJE TERETNJAKA",
        "ui.aisPassengerVessel": "AIS PUTNIČKI BROD",
        "ui.aisYachtSignal": "AIS SIGNAL JAHTE",
        "ui.aisMilitaryVessel": "AIS VOJNI BROD",
        "ui.carrierStrikeGroup": "UDARNA GRUPA NOSAČA",
        "ui.aisVesselSignal": "AIS SIGNAL PLOVILA",
        "ui.militaryIncidentCluster": "VOJNI INCIDENTNI KLASTER",
        "ui.vessel": "PLOVILO",
        "ui.aircraftCarrier": "NOSAČ AVIONA",
        "ui.tanker": "TANKER",
        "ui.cargoVessel": "TERETNI BROD",
        "ui.passengerCruise": "PUTNIČKI / KRSTAREĆI",
        "ui.privateYacht": "PRIVATNA JAHTA",
        "ui.militaryVessel": "VOJNI BROD",
        "ui.latestReports": "NAJNOVIJI IZVEŠTAJI:",
        "ui.viewSourceReport": "Prikaži izvorni izveštaj",
        "ui.regionalTacticalEvent": "REGIONALNI TAKTIČKI DOGAĐAJ",
        "ui.viewDetails": "Prikaži detalje",
        "ui.newsOnTheGround": "VESTI SA TERENA",
        "ui.noArticlesAvailable": "Nema dostupnih članaka.",
        "ui.viewSourceArticle": "Prikaži izvorni članak",
        "ui.threatIntercept": "PRESRETANJE PRETNJE",
        "ui.viewIntelSource": "Prikaži izvor obaveštajnih podataka",
        "ui.viewHistoryLog": "Prikaži istoriju",
        "ui.aeronauticalHub": "AERONAUTIČKI ČVOR",
        "ui.facilityName": "NAZIV OBJEKTA",
        "ui.status": "STATUS",
        "ui.operational": "OPERATIVNO",
        "ui.locationPrefix": "LOKACIJA:",
        "ui.articleCount": "BROJ ČLANAKA",
        "ui.headline": "NASLOV",
        "ui.reference": "REFERENCA",
        "ui.time": "VREME",
        "ui.source": "IZVOR",
    },
};

interface UiLanguageContextValue {
    language: UiLanguage;
    setLanguage: React.Dispatch<React.SetStateAction<UiLanguage>>;
    t: (key: string) => string;
}

export const UiLanguageContext = createContext<UiLanguageContextValue | null>(null);

export function UiLanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<UiLanguage>("sr-Latn");

    useEffect(() => {
        try {
            const saved = window.localStorage.getItem(STORAGE_KEY);
            if (saved === "en" || saved === "sr-Latn") {
                setLanguage(saved);
            }
        } catch {
            // Ignore storage failures and keep the default language.
        }
    }, []);

    useEffect(() => {
        try {
            window.localStorage.setItem(STORAGE_KEY, language);
        } catch {
            // Ignore storage failures.
        }
        document.documentElement.lang = language;
    }, [language]);

    const value = useMemo<UiLanguageContextValue>(() => {
        return {
            language,
            setLanguage,
            t: (key: string) => STRINGS[language][key] ?? STRINGS.en[key] ?? key,
        };
    }, [language]);

    return <UiLanguageContext.Provider value={value}>{children}</UiLanguageContext.Provider>;
}

export function useUiLanguage() {
    const value = useContext(UiLanguageContext);
    if (!value) {
        throw new Error("useUiLanguage must be used within a UiLanguageProvider");
    }
    return value;
}
